Validation of contracts
HLTech/vaunt pull request #25
Opened 2019-04-19 14:20 UTC by Felipe444

2019-04-19 16:22 UTC, matek2305 requested changes

2019-04-19 16:22 UTC, matek2305 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +public class ValidationResult {
maybe add factory methods for successful and failed validation so there wont be need to pass `isValid` argument?

2019-04-19 16:32 UTC, matek2305 requested changes

2019-04-19 16:32 UTC, matek2305 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/VauntValidator.java
> +        return new ValidationResult(true, Lists.newArrayList());
with factory method it could be written like that: `return ValidationResult.success();` with no need to expose internal implementation here

2019-04-19 18:53 UTC, garlicsauce commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/VauntValidator.java
> +
remove blank line

2019-04-19 18:53 UTC, garlicsauce commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +    private final List<String> errors;
We could make it sth like
`private final List<ValidationError> errors;`
where `ValidationError` is an enum with list of possible validation issues.

2019-04-19 18:53 UTC, garlicsauce commented on vaunt-validator/src/test/groovy/com/hltech/vaunt/validator/VauntValidatorSpec.groovy
> +            ArrayListMultimap<String, Contract> providerNameToContracts = ArrayListMultimap.create()
mark separate sections with `and:`

2019-04-19 18:53 UTC, garlicsauce commented on vaunt-validator/src/test/groovy/com/hltech/vaunt/validator/VauntValidatorSpec.groovy
> +            validationResults = validator.validate(Lists.newArrayList(consumerContract), Lists.newArrayList(providerContract))
I guess it would be nice to have it in separate test

2019-04-20 16:02 UTC, garlicsauce approved these changes

2019-04-22 15:41 UTC, matek2305 requested changes

2019-04-22 15:41 UTC, matek2305 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +    public static ValidationResult failure(List<ValidationError> errors) {
i would consider using varargs here so signature will look like this `public static ValidationResult failure(ValidationError... errors);` usage will bo more friendly imo coz we wont need to use something to create list

2019-04-22 18:48 UTC, Felipe444 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +    public static ValidationResult failure(List<ValidationError> errors) {
it can be varargs, it can be list as well :)

2019-04-22 19:11 UTC, garlicsauce approved these changes

2019-04-22 19:18 UTC, matek2305 requested changes

2019-04-22 19:18 UTC, matek2305 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +    public static ValidationResult failure(List<ValidationError> errors) {
i know that, but with varargs usage will be a lot better coz you will be writing it like this:
`return ValidationResult.failure(ValidationError.SOMETHING);` without need to create list (it will be hidden)

2019-04-22 19:30 UTC, Felipe444 commented on vaunt-validator/src/main/java/com/hltech/vaunt/validator/ValidationResult.java
> +    public static ValidationResult failure(List<ValidationError> errors) {
I know, for me it is a total minor :)

2019-04-22 19:30 UTC, matek2305 approved these changes

2019-04-22 20:06 UTC, merged