Write service representation to file as json.
HLTech/vaunt pull request #26
Opened 2019-04-19 15:05 UTC by matek2305

2019-04-19 19:18 UTC, garlicsauce commented on vaunt-generator/src/test/groovy/com/hltech/vaunt/generator/VauntGeneratorSpec.groovy
> +            def packageName = 'dev.hltech.transferout.informationrequest'
truly real-life example xD

2019-04-19 19:20 UTC, garlicsauce approved these changes

2019-04-20 14:59 UTC, Felipe444 requested changes

2019-04-20 14:59 UTC, Felipe444 commented on build.gradle
> +        testRuntimeOnly "net.bytebuddy:byte-buddy:1.9.12"
let's keep versions in one place

2019-04-20 14:59 UTC, Felipe444 commented on vaunt-generator/build.gradle
> +    testCompile 'com.jayway.jsonpath:json-path-assert:2.2.0'
same here

2019-04-20 14:59 UTC, Felipe444 commented on vaunt-generator/src/main/java/com/hltech/vaunt/generator/VauntGenerator.java
>  public class VauntGenerator {
Let's make VauntGenerator an orchestrator, i. e. firstly it calls RepresentationExtractor, later it calls VauntWriter; or something similar.

2019-04-20 14:59 UTC, Felipe444 commented on vaunt-generator/src/test/groovy/com/hltech/vaunt/generator/VauntGeneratorSpec.groovy
> +            def packageName = 'dev.hltech.transferout.informationrequest'
let's change it to something different

2019-04-23 19:35 UTC, Felipe444 commented
Please add task to create custom exceptions policy.

2019-04-23 19:35 UTC, Felipe444 approved these changes

2019-04-23 19:45 UTC, merged